version: '3'

services:
    gate:
        build: .
        container_name: gate-development
        environment:
            - PROXY_PORT=80
            - FORWARD_URL=http://host.docker.internal:1234
            - JWT_SECRET=thisissomesecretornot
        ports:
            - 9090:80
        volumes:
            - ./build:/app/src
